### ISSUE TITLE
Can't get version of packages published under an org

### ISSUE THREAD

**Issue by bennypowers** [divriots/webcomponents.dev#33]
**Describe the bug**
I moved a component to `apollo-elements` org: https://webcomponents.dev/edit/n67sjuzH56J05LOLnxx0
Once I published 0.0.1 or 0.1.0 or 1.0.0, I can no longer publish, because the `Current Version` remains "None"

**To Reproduce**
1. Create a component
2. Transfer it to an organization
3. publish v0.1.0
4. Reload the page
5. Attempt to publish minor (v0.1.0) - can no longer publish

**Expected behavior**
I should get the current version

**Device**
 - OS: macOS catalina
 - Browser: Firefox
 - Version: 84

**Comment by georges-gomes** [comment]
Yes, there is a bug. You shouldn't be able to deploy on @wcd scope once you are on a org. You need to have your own scope.

Click your avatar menu, select preferences, then select the org instead of your name.
Go to integration and look for npm scopes. You should be able to add a npm access token to pushing to you scope.

Prerequisite is to create the @apollo-elements scope on npm. (You can use any scope name that you own)

**Comment by gqio** [comment]
@bennypowers I'm closing this one, this has been addressed. If you encounter any other issue please reopen it or raise another issue.
