### ISSUE TITLE
Uncaught TypeError: _missingExportShim is not a function

### ISSUE THREAD

**Issue by tpluscode** [divriots/webcomponents.dev#67]
### 📖 Reproduction steps

1. Go to https://webcomponents.dev/edit/O8SwE2klRV1wMB87Rkh2/src/index.js
2. Switch to branch `material`
3. Uncomment lines in `index.js`

### 🙁 Current Behavior

Project does not build with error

### 🙂 Expected Behavior

Should run fine

### 🌐 What browser(s) are you seeing the problem on?

Chrome

**Comment by gluck** [comment]
Hi, the error is pretty shady, but it's caused by conflicting requirements on lit-html versions.
`@hydrofoil/shaperone-wc-material` depends on `lit@^2` but also on `@material/mwc-*@^0.20.0`, which themselves depend on `lit-element@^2` (aka `lit-html@^1`).

You need to bump material to `0.25+` to get lit v2 compatibility AFAIK.

LMK if that helps

**Comment by gluck** [comment]
It's possible the bundler could include both versions, but TBH I've seen the opposite requirement way more often (duplicate versions of `react` being bundled causing errors, so was the case with `lit-html` until recently IIRC).

It's actually suprising it fails because we only dedupe direct dependencies, and you haven't specified `lit-html` in your `package.json`, so it should _not_ be deduped.

But changing that logic may affect many components, so I'll be extra careful before changing it.

Thanks.

**Comment by tpluscode** [comment]
Alright, I updated the material packages so that everything should be running `lit@2`. 

The `_missingExportShim` error is gone, so the major version conflict is gone but it still appears that there is a duplicate resolution given the output. Instead of rendering HTML, function code renders. A typical indication of multiple `html` functions being imported

**Comment by tpluscode** [comment]
Finally, I'm out of ideas. I removed the dependency on `lit` and only use what import and re-export from `@hydrofoil/shaperone-*` packages

Still not rendering correctly :(

**Comment by tpluscode** [comment]
Hm, one more thing. Turns out that if I comment out the line `renderer.setTemplates(MaterialRenderStrategy)` the rendering is correct

**Comment by gluck** [comment]
That's getting out of my league, I can confirm there's only one copy of lit/lit-html/lit-element in the bundle though ...

**Comment by tpluscode** [comment]
Interesting. Thank you for checking that. Would appreciate if someone could take a look.

I have not tried, but will I be able to check out my playground locally and debug stuff myself?

**Comment by gluck** [comment]
You'll have to setup a build toolchain for that, we do provide a local/CLI setup, but that's only for the IDE experience, and still using our online toolchain.

**Comment by gqio** [comment]
Hi @tpluscode ,

Don't know if it may help or maybe you already tried that but you can put a `debugger;` statement inside the code and you can inspect with dev tools the processing of the lib.

I don't know shaperone so it will be hard for me to help you on that part.

Like after inspecting your component, lit try to render a function. Is something you expect ?
![image](https://user-images.githubusercontent.com/1063530/142498794-824ee03a-b566-426c-9a50-4b8fa93f1ed8.png)

**Comment by georges-gomes** [comment]
@tpluscode worth case scenario you can connect your playground to GitHub and then check it our to your local machine.
But as mentioned by @gluck you need to setup a build.

**Comment by georges-gomes** [comment]
@jorenbroekema is our Lit black belt, maybe he has an idea ?

**Comment by tpluscode** [comment]
Oh, thank you so much for the hint. It was my mistake after all. I was so hung up on the function being rendered I could only think of lit-html's fault.

Ok, nothing to look at here.
