### ISSUE TITLE
Cannot read properties of undefined (reading 'mediumTimeFormat')

### ISSUE THREAD

**Issue by MEPacana** [divriots/webcomponents.dev#74]
### 📖 Reproduction steps

1. Create LWC Project
2. Go to app.html
3. Try using lightning-input
```
<template>
	<div class="slds-m-around_medium">
		<lightning-input label="Test"></lightning-input>
	</div>
</template>
```
4. Compile
5. See error

### 🙁 Current Behavior

Unable to compile code using lightning-input. It causes an error 
`Cannot read properties of undefined (reading 'mediumTimeFormat')`

### 🙂 Expected Behavior

Able to use lightning-input component

### 🌐 What browser(s) are you seeing the problem on?

Chrome

**Comment by MEPacana** [comment]
![image](https://user-images.githubusercontent.com/21273357/180379210-68e7955d-8fa2-4047-9ffb-65103fba3816.png)

**Comment by bashmish** [comment]
Related https://github.com/salesforce/lwc/issues/2946 , but the other report was also tested in webcomponents.dev, so not necessarily a LWC core bug

**Comment by bashmish** [comment]
Turns out to be an issue with latest [lightning-base-components@1.15.3-alpha](https://www.npmjs.com/package/lightning-base-components/v/1.15.3-alpha)

You can workaround this by setting the previous working version `1.15.2-alpha` in `lwc.config.json`:

```
{
  "modules": [
    {
      "npm": "lightning-base-components@1.15.2-alpha"
    },
    {
      "dir": "src"
    }
  ]
}
```

But I think the eventual fix should be done on their side.

Credit to @gluck for finding the root cause.

**Comment by bashmish** [comment]
As of `lightning-base-components@1.15.4-alpha` released a few minutes ago the workaround is not needed anymore, I mean you can't just keep the config as is when creating an LWC Project.
